### ISSUE TITLE
Building fails when cross-compiling from linux

### ISSUE THREAD

**Issue by tree786** [EstebanBorai/local-ip-address#16]
Hallo

I am having issue trying to cross compile from linux (using manjaro) . It compiles fine when I build on manjaro, however, when trying to cross compile (using [cross](https://crates.io/crates/cross) crate)
```
error: couldn't read /target/x86_64-pc-windows-gnu/release/build/local-ip-address-d09fce1ffe5cd6c7/out/windows.rs: No such file or directory (os error 2)
 --> /cargo/registry/src/github.com-1ecc6299db9ec823/local-ip-address-0.4.2/src/windows.rs:2:5
  |
2 |     windows::include_bindings!();
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `::std::include` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `local-ip-address` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed

```
I am using this command to compile: `cross build --release --target x86_64-pc-windows-gnu`

I am not sure what that mean? is there a way to overcome this when cross compiling from manjaro?

Thank s

**Comment by EstebanBorai** [comment]
Hi @tree786! Based on the provided output and the fact that you are cross-compiling the project for Windows using Linux as host, I can tell your issue is related to Windows system libraries that are not available on Linux.

The log complains about the `include_bindings` macro because bindings to Windows system libraries are generated and included into the crate on build time. Given that you are cross-compiling your project on Linux, native Windows libraries are not available causing this error.

This line:

```rust
windows::include_bindings!()
```

Expands to: https://docs.rs/windows/0.18.0/src/windows/macros.rs.html#3-7 , as bindings are not generated, the `windows.rs` file will is not available. That's why we are getting this error here:

```log
error: couldn't read /target/x86_64-pc-windows-gnu/release/build/local-ip-address-d09fce1ffe5cd6c7/out/windows.rs No such file or directory (os error 2)
```

The crate used to interact with Windows Win32 API is https://github.com/microsoft/windows-rs, this issue is already being tracked by the contributors of such crate here: https://github.com/microsoft/windows-rs/issues/638

Usually what I do to build this crate on Windows is to use GitHub Actions, here is the workflow in question: https://github.com/EstebanBorai/local-ip-address/blob/6cd706b8c9f41c3f6659f86b4e7d037812241a3e/.github/workflows/build.yml#L17

I'm not sure what are you are working on, but if it works for you to have GitHub Actions build the project for you I think you could workaround the issue  using GHA instead, that way DLLs will be available on build time and this error won't occur anymore.

Hope this help, please ask any questions if needed!

**Comment by tree786** [comment]
Hi, thanks for answer ! i have not used GHA before, so i think i will need to investigate it and understand it better, but thanks for pointers ! (also you can close this issue if you wish)

**Comment by EstebanBorai** [comment]
> Hi, thanks for answer ! i have not used GHA before, so i think i will need to investigate it and understand it better, but thanks for pointers ! (also you can close this issue if you wish)

Sure thing! Thanks to you!
