### ISSUE TITLE
Windows 10 Chinese version is not supported

### ISSUE THREAD

**Issue by axxop** [EstebanBorai/local-ip-address#18]
I am using the Chinese version of windows 10, when I use this library, the program terminates and throws an error `UnsupportPlatform(Windows)` 

I quickly browsed the library code and found that English hard-coded query conditions are used here `Ethernet` :
[https://github.com/EstebanBorai/local-ip-address/blob/main/src/lib.rs#L111](url)

On Windows 10 Chinese operating system, the name will be `以太网` .

Similar problems may exist on windows systems that use other languages. Is there a better solution?

**Comment by EstebanBorai** [comment]
Hey @axxop , this sounds awful I'm sorry about the issue.

I'll investigate this and get back to this thread when I have a solution. We are using `windows-rs` to consume Win32 API through Rust if you want to take the lead and work on a solution I would be very happy to help you.

Keep you tuned!

**Comment by EstebanBorai** [comment]
Hi @axxop!

I have been researching the issue and I believe the error core is the use of `FriendlyName` instead of `AdapterName` when searching for network interfaces on Windows.

This is the line in question:

https://github.com/EstebanBorai/local-ip-address/blob/6f4ada754ed2e2d4a6859019349bf64c3855bd23/src/windows.rs#L72

`FriendlyName` name is likely to change, it is intended to be easy to understand for system network applications such as `ipconfig`, so instead of having a `en0` as you would do for macOS for instance, you will find the user's custom name or `Ethernet` which is the de-facto in English Windows versions.

I would give a shot on `AdapterName` instead based on this extract from the struct documentation:

_Unlike an adapter's friendly name, the adapter name specified in AdapterName is permanent and cannot be modified by the user._

[Documentation](https://docs.microsoft.com/en-us/windows/win32/api/iptypes/ns-iptypes-ip_adapter_addresses_lh)

I still have to run a version with this change and analyze the results, but the fact that the name in `AdapterName` is _permanent and cannot be modified by the user_ makes it more safe to use instead of relying on the "label" value.

Let me know your thoughts!

**Comment by EstebanBorai** [comment]
@axxop I've openned a PR where you can have a look and also give a try to the approach mentioned earlier.
Please let me know any issues you found and your suggestions. Hope this helps.

**Comment by axxop** [comment]
Sorry for the delay in reply,

I think it is necessary to get the local ip through the default route. This will handle the case of multiple network cards (tun, eth, wifi). When the system does not have a default route, the local_ip method will fail explicitly. At this time, the developer needs to process it through list_inteface.

What do you think?

**Comment by EstebanBorai** [comment]
@axxop sounds good to me! But I'm not sure what are you referring to with _default route_, I really appreciate if you elaborate a bit please?

`local_ip` is expected to fail when changes has been made to the default network configuration in your system.

And you can always list all your networks and make attempts on the network interface you want to gather.

**Comment by EstebanBorai** [comment]
@axxop sounds good to me! But I'm not sure what are you referring to with _default route_, I really appreciate if you elaborate a bit please?

`local_ip` is expected to fail when changes has been made to the default network configuration in your system.

And you can always list all your networks and make attempts on the network interface you want to gather.

**Comment by axxop** [comment]
`Defautl route` wiki: [Defautl route](https://en.wikipedia.org/wiki/Default_route)

**Comment by EstebanBorai** [comment]
Yeah sounds good to me! Thanks for the specification!
I just have to identify the Default Route in the set of network interfaces and I think we will be good to go!

**Comment by EstebanBorai** [comment]
@axxop I have been checking on whats available in the [`GetAddaptersAddresses`](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/NetworkManagement/IpHelper/fn.GetAdaptersAddresses.html) function from windows-rs but I don't seem to find a realiable way to gather the default gateway.

The best approach so far is using the  `DnsSuffix` as I did in the PR IMHO, do you have any suggestions?
Perhaps we could use different conditions and gather the first Network Interface that matches one of the conditions?

I'm also trying to get the Network Interface which has a "Default Gateway" property and such property points to either
`192.168.1.1` or `0.0.0.0`. I need to continue working on it, but what do you think about the approach?

Any suggestions are welcome, thanks in advance!

**Comment by EstebanBorai** [comment]
> I just wrote this up. This way works for me (using `windows-rs`) to detect the locally used IP. You are free to use it if you find it useful.
> 
> (Shamelessly [stolen from StackOverflow](https://stackoverflow.com/a/24664853/9423933))
> 
> Note: _you might want to change the IP from google to something else that is fine accepting these, cause who knows, google may block an IP due to a "high number of requests"_
> 
> ```toml
> [dependencies.windows]
> version = "0.37.0"
> features = [
>     "Win32_Networking_WinSock",
>     "Win32_Foundation",
>     "alloc"
> ]
> ```
> 
>  ```rust
> pub fn get_local_ip() -> String {
>     // connect a local socket in order to determine the local ip used
>     unsafe {
>         let mut data = WSAData::default();
>         let ret = WSAStartup(0x202, &mut data);
>         assert_eq!(ret, 0);
> 
>         let socket = socket(AF_INET.0 as i32, SOCK_STREAM as i32, IPPROTO_TCP.0);
> 
>         let mut remoteaddr = SOCKADDR_IN::default();
>         remoteaddr.sin_family = AF_INET.0 as u16;
> 
>         let mut in_addr = IN_ADDR::default();
>         // google's IP
>         let inet_addr = inet_addr("142.250.217.142");
>         in_addr.S_un = IN_ADDR_0 { S_addr: inet_addr };
>         remoteaddr.sin_addr = in_addr;
> 
>         remoteaddr.sin_port = htons(80);
> 
>         let con = connect(socket, &remoteaddr as *const _ as *const SOCKADDR, std::mem::size_of::<SOCKADDR>() as i32);
> 
>         let mut address = None;
>         if con == 0 {
>             let mut localaddr = SOCKADDR_IN::default();
>             let mut len = std::mem::size_of_val(&localaddr) as i32;
> 
>             getsockname(socket, &mut localaddr as *mut _ as *mut SOCKADDR, &mut len as *mut i32);
>             let pstr_address: PSTR = inet_ntoa(localaddr.sin_addr);
> 
>             let c_str = CStr::from_ptr(pstr_address.0 as *const _).to_str().unwrap();
>             address = Some(c_str.to_string());
>         }
> 
>         closesocket(socket);
>         WSACleanup();
> 
>         if let Some(addr) = address {
>             return addr;
>         }
> 
>         panic!("Couldn't find local IP address. Error: {}", WSAGetLastError().0);
>     }
> }
> ```

Thanks for this snippet @cherryleafroad!

Yeah, I'm familiar with this approach, but what I don't like is the fact of relying on fetching an internet resource, because this would involve internet connection in order to have the crate working.

I have been checking on other strategies for windows to fix this issue, given that is actually a bad idea to rely on the Network Interface's table `FriendlyName` on Windows.

**Comment by hummingly** [comment]
I think I have found a reliable solution for Windows. You can get the default route by querying the routing table returned by [GetIpForwardTable](https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getipforwardtable). The documentation notes how to get the default route.

> An IPv4 address of 0.0.0.0 in the dwForwardDest member of the MIB_IPFORWARDROW structure is considered a default route.

I have made a publicly available [gist](https://gist.github.com/hummingly/9badaabdfc239bed7628b4fdc367ebf4) showing how to get all local IP addresses.

A similar technique should work on unix too with netlink where you can also get the routing table and filter addresses from getifaddrs. I think this would be an improvement because there can be multiple adapters with "en0"; though I have no source to prove that. This would allow to create a cross platform and reliable solution. For context I want to get the local IP address for mobile devices and desktop for my hobby project.

**Comment by EstebanBorai** [comment]
Hi @hummingly! Thanks so much for your insight, its very helpful!
This helps me point into the right direction to solve this issue.

Do you feel like opening a PR at some point? It would be very helpful at this time.
Let me know if you are interested please, or just open the PR when you are ready if thats the case.
