### ISSUE TITLE
Hope to support FreeBSD OS

### ISSUE THREAD

**Issue by m00nfly** [EstebanBorai/local-ip-address#40]
My project uses the local-ip-address dependency library and it runs normally. Thank you very much for your creation;

But now I have a problem when I want to port the project to the FreeBSD platform. The local-ip-address library cannot be compiled on the FreeBSD12 platform;

I have seen in the release of this project that the FreeBSD system is not supported,
But I still want to know if the author has plans to support FreeBSD OS in the future?

Thanks again for your work!

The following errors I encountered when compiling under the FreeBSD12 platform, I hope to help you

error[E0308]: mismatched types
--> /root/.cargo/registry/src/github.com-1285ae84e5963aae/local-ip-address-0.4.4/src/lib.rs:86:22
|
86 | pub fn local_ip() -> Result<IpAddr, Error> {
| -------- ^^^^^^^^^^^^^^^^^^^^^ expected enum Result, found ()
| |
| implicitly returns () as its body has no tail or return expression
|
= note: expected enum Result<IpAddr, Error>
found unit type ()

For more information about this error, try rustc --explain E0308.
error: could not compile local-ip-address due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by EstebanBorai** [comment]
Hi @m00nfly! I'm glad you are using this crate!

I'm sorry to hear that you can't get `local-ip-address` to run on your FreeBSD system, having support for that platform would be awesome but I would need some help with the implementation because I'm not familiar with FreeBSD at all and I would need to setup some environment to have it running and develop closer to the system.

Do you feel like implementing it as a contribution? I also have plans to extend the current API to bring system specific details but I have been very busy lately.

**Comment by rtyler** [comment]
This project now builds and tests pass on FreeBSD, so I think this can be closed

**Comment by EstebanBorai** [comment]
Thanks for supporting this @rtyler!
